name: Fechar milestones vencidas

on:
  schedule:
    - cron: "0 3 * * *" # Executa diariamente as zero hora do horario de brasilia
  workflow_dispatch:

permissions:
  issues: write

jobs:
  fechar-milestones: # Considere uma milestone como as sprints e suas issues vinculadas
    runs-on: ubuntu-latest
    steps:
      - name: Fechar milestones e issues vencidas
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const now = new Date();
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            // Pega todas as milestones abertas
            const milestones = await github.paginate(
              github.rest.issues.listMilestones,
              { owner, repo, state: 'open', per_page: 100 }
            );

            const expiradas = milestones.filter(m => m.due_on && new Date(m.due_on) < now);

            // Fecha as milestones vencidas e suas issues vinculadas
            for (const milestone of expiradas) {
              core.info(`Fechando milestone #${milestone.number} - ${milestone.title}`);

              await github.rest.issues.updateMilestone({
                owner,
                repo,
                milestone_number: milestone.number,
                state: 'closed'
              });

              const issues = await github.paginate(
                github.rest.issues.listForRepo,
                { owner, repo, state: 'open', milestone: milestone.number, per_page: 100 }
              );

              for (const issue of issues) {
                core.info(`Fechando issue #${issue.number} vinculada à milestone #${milestone.number}`);
                await github.rest.issues.update({
                  owner,
                  repo,
                  issue_number: issue.number,
                  state: 'closed'
                });
              }
            }

            // Caso não tenha milestones vencidas
            if (!expiradas.length) {
              core.info('Nenhuma milestone vencida encontrada.');
            }